changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feat
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "🔧 Other Changes"
      labels:
        - "*"
